## CIND830 - Python Programming for Data Science  
### Assignment 3 (10% of the final grade)

*****
This is a Jupyter Notebook document that extends a simple formatting syntax for authoring HTML and PDF.
Review [this](https://jupyter-notebook.readthedocs.io/en/stable/notebook.html) website for more details on using Jupyter Notebook.

Use the JupyterHub server on the Google Cloud Platform,
provided by your designated instructor, for this assignment.
Complete the assignment by inserting your Python code wherever you see the string
"#INSERT YOUR ANSWER HERE." or "##CODE HERE##"

When you click the `File` button, from the top navigation bar, then select `Export Notebook As ...`,
a document (PDF or HTML format) will be generated that includes
 both the assignment content and the output of any embedded Python code chunks.

Using [these](https://www.ryerson.ca/courses/students/tutorials/assignments/) guidelines,
submit **both** the IPYNB and the exported file (PDF or HTML).
Failing to submit both files will be subject to mark deduction.

*****

### Question 1:

**a)** Write a code segment to create and print a two-dimensional 5x4 array (i.e. grid). The elements of the grid should be randomly selected from the inclusive interval \[-50, 50\].

In [1]:
#INSERT YOUR ANSWER HERE.
import numpy as np 
ranArr=np.random.randint(-50,50,size=(5,4))
print(ranArr)
os.getcwd()


[[-32  13 -18 -38]
 [-23 -36 -28 -15]
 [-27  25 -29  27]
 [-29  36 -11 -29]
 [ -3   4  30 -35]]


'c:\\Users\\mcken\\Desktop\\Big Data Analytics Class\\CIND 830\\Assignments'

In [12]:
class Course: 
    def code(self, id = '820'):
        print(id)
P = Course()
P.code('830')

830


**b)** Write a code segment that searches the `Grid` object in `Q1a` for all the negative integers, and prints them.

In [2]:
negtiveNum=[]
len(ranArr)
for i in ranArr:
    for nm in i:
        if nm <0: 
            negtiveNum.append(nm)
print(negtiveNum)

[-38, -44, -13, -27, -3, -17, -9, -20, -36, -43]


**c)** Given that `iList = [1, -1, 2, -2]`, add each element of `iList` to its corresponding element of `Q1a` `Grid` row-wise.  

For example, if the Grid is equal to: $$\begin{pmatrix} 1 & 2 & 1 & 1 \\ 3 & 0 & 1 & 6 \\ 0 & 2 & 4 & 6 \\ 4 & 5 &0 & 2 \\ 3 & 6 & 4 & 3 \end{pmatrix}$$

Then the output should be:
$$\begin{pmatrix} 1+1 & 2-1 & 1+2 & 1-2 \\ 3+1 & 0-1 & 1+2 & 6-2 \\ 0+1 & 2-1 & 4+2 & 6-2 \\ 4+1 & 5-1 &0+2 & 2-2 \\ 3+1 & 6-1 & 4+2 & 3-2 \end{pmatrix}$$

In [60]:
ranArrCopy = ranArr.copy()
iList=[1,-1,2,-2]
print(ranArrCopy)
ranArrCopy=ranArrCopy+iList
print("\n",ranArrCopy)


[[-29 -46 -16  49]
 [ 18 -31 -39 -48]
 [-37  48  11 -38]
 [-24  33 -22  10]
 [ 48 -25 -41 -45]]

 [[-28 -47 -14  47]
 [ 19 -32 -37 -50]
 [-36  47  13 -40]
 [-23  32 -20   8]
 [ 49 -26 -39 -47]]


**d)** Write a code segment that creates a ragged grid with three rows.  The first row contains 2 positions, the second row contains 4 positions, and the third row contains 6 positions. 

In [3]:
#Array class
class nArray():
    def __init__(self,capacity,fillValue = None):
        self._items=list()
        for count in range(capacity):
            self._items.append(fillValue)

    def __getitem__(self,index):
        return self._items[index]

    def __setitem__(self,index,newItem):
        self._items[index]=newItem

    def __len__(self):
        return len(self._items)

    def __str__(self):
        return str(self._items)

    def __iter__(self):
        return iter(self._items)

class ragGrid():

    def __init__(self,rows,*col):
        self._data = nArray(rows)
        for row in range(rows):
            self._data[row]=nArray(col[row])
    
    def gRows(self):
        return len(self._data)
            
    def gCols(self,row_in=None):
        if row_in is None:
            return [len(self._data[row]) for row in self._data]
        else:
            return len(self._data[row_in])

    def __str__(self):
        result = "\n"
        for row in range(self.gRows()):
            for col in range(self.gCols(row)):
                result += repr(self._data[row][col])+ ' '
            result += '\n'
        return result

first=ragGrid(3,2,4,6)
print(first)



None None 
None None None None 
None None None None None None 





### Question 2:
A search algorithm `iSearch` and a variable `ilist` have been defined as follows:




In [4]:
def iSearch(target, lyst):
    left = 0
    right = len(lyst) - 1
    while left <= right:
        midpoint = (left + right) // 2
        if target == lyst[midpoint]:
            return midpoint
        elif target < lyst[midpoint]:
            right = midpoint - 1
        else:
            left = midpoint + 1
    return -1

iList = [11, 20, 29, 33, 41, 55, 56, 62, 66, 74, 88]
print(iSearch(11,iList))

0


**a)**  If the target element is `11`, trace the values of the variables `left`, `right`, and `midpoint` after applying the `iSearch` algorithm to the `iList` structure. 



In [6]:
# 437
def iSearch(target, lyst):
    left = 0
    right = len(lyst) - 1
    print("%10s%10s%10s" % ("Midpoint","Left","Right"))
    while left <= right:
        midpoint = (left + right) // 2
        if target == lyst[midpoint]:
            return midpoint
        elif target < lyst[midpoint]:
            right = midpoint - 1
        else:
            left = midpoint + 1
        print("%10s%10s%10s" %(midpoint,left,right))
    return -1

print(iSearch(11,iList))


  Midpoint      Left     Right
         5         0         4
         2         0         1
0


**b)**  Repeat the tracing process in `Q1a` for target element `55`.

In [7]:

def iSearch(target, lyst):
    left = 0
    right = len(lyst) - 1
    if target != lyst[(left+right)//2]:
        print("%10s%10s%10s" % ("Midpoint","Left","Right"))
    while left <= right:
        midpoint = (left + right) // 2
        if target == lyst[midpoint]:
            return midpoint
        elif target < lyst[midpoint]:
            right = midpoint - 1
        else:
            left = midpoint + 1
        print("%10s%10s%10s" %(midpoint,left,right))
    return -1

print(iSearch(55,iList))


5


**c)**  Why does the iSearch algorithm run faster in `Q1b` scenario than in `Q1a` scenario?

In [ ]:
#INSERT YOUR ANSWER HERE.
# The search algorithm runs faster in Q1b than Q1a because the best-case scenrario occurs in Q1b, O(1). The functions checks the middle value first and 55 happened to be the middle value so the rest of the code did not need to run. 

**d)** Modify the `iSearch` algorithm, so it can run in `Q1a` scenario as fast as it does in `Q1b` scenario.

In [13]:
#INSERT YOUR ANSWER HERE.
def iSearch(target, lyst):
    position = 0
    while position <len(lyst):
        if target == lyst[position]:
            return position
        position += 1
    return -1

print(iSearch(11,iList))


0


**e)** For a problem of size $n$, if algorithm `X` performs $n^4$ instructions, and algorithm `Y` performs $2^n$ instructions.  At what point does one of the algorithms begin to be more efficient and perform better than the other? Justify your answer.

In [ ]:
#INSERT YOUR ANSWER HERE.
"Algorithim Y is exponential meaning that it has a the highest order of complexity.Y would be less efficient as it enters a for loop."

*****

### Question 3:



Emulate the stack behaviour using the list data structure.

**a)** Complete the methods of the following `Stack` class according to their description

In [8]:

class Stack:
  def __init__(self):
    """ Initialize a new stack """
    self.elements = []
    self._top = -1
    self._size = 0
  def push(self, new_item):
    """ Append the new item to the stack """
    self._top += 1
    self._size += 1 
    self.elements.append(new_item)
  def pop(self):
    """ Remove and return the last item from the stack """
    oldItem = self.elements.pop(self._top)
    self._top -= 1
    self._size -=1
    return oldItem
  def size(self):
    """ Return the total number of elements in the stack """
    return self._size
  def is_empty(self):
    """ Return True if the stack is empty and False if it is not empty """
    return len(self.elements)==0
  def peek(self):
    """ Return the element at the top of the stack or return None if the stack is empty """
    return self.elements[self._top]




True

**b)** Use the `Stack` class that you defined in `Q3a` to complete the code of the `is_valid()` function, which checks whether the order of the brackets of an arithmetic expression is correct. Some examples are given below:

In [9]:
exp1 = "(2+3)+(1-5)" # True
exp2 = "((3*2))*(7/3))" # False
exp3 = "(3*5))]" # False

In [10]:
def is_valid(exp):
  """ Check the order of the brackets
      Returns True or False
  """
  emp = Stack()
  opening = ['(', '[', '{']
  closing = [')', ']', '}']
  for br in exp:
    if br in opening:
      emp.push(br)
    elif br in closing: 
      if emp.is_empty():
        return False
      brFromStack = emp.pop()
    if br == closing[0] and brFromStack != opening[0] or \
        br == closing[1] and brFromStack != opening[1] or \
          br == closing[2] and brFromStack != opening[2]:
          return False
  return emp.is_empty()
  
is_valid(exp1)
is_valid(exp2)
is_valid(exp3)

False

**c)** Use the `Stack` class that you defined in `Q3a` to complete the code of the `count_pairs()` function, which returns the number of the valid bracket pairs of an arithmetic expression. Some examples are given below:

In [22]:
exp1 = "(2+3)+(1-5)" # 2 pairs
exp2 = "((([()])))" # 5 pairs
exp3 = "[([])" # 2 pairs

In [31]:
def count_pairs(exp):
    expop = Stack()
    expcl = Stack()
    opening = ['(','[','{']
    closing = [')',']','}']
    pairs = 0
    for ch in exp:
        if ch in opening:
            expop.push(ch)
        elif ch in closing:
            expcl.push(ch)
    
    if expop.size() == expcl.size():
        expoplist = []
        expcllist = []
        for ex in range(expop.size()):
            a = expop.pop()
            expoplist.append(a)
        for excl in range(expcl.size()):
            b = expcl.pop()
            expcllist.append(b)
         
        for cl in range(len(expcllist)):
            while len(expcllist)>0:
                c=expcllist.pop(0)
                d=expoplist.pop()
                if c == closing[0] and d == opening[0] or c == closing[1] and d==opening[1] or c == closing[2] and d==opening[2]:
                    pairs+=1
    elif expop.size() > expcl.size():
        expoplist = []
        expcllist = []
        for ex in range(expop.size()):
            a = expop.pop()
            expoplist.append(a)
        
        for excl in range(expcl.size()):
            b = expcl.pop()
            expcllist.append(b)
        
        for cl in range(len(expcllist)):
            while len(expcllist)>0:
                c=expcllist.pop()
                d=expoplist.pop()
                if c == closing[0] and d == opening[0] or c == closing[1] and d==opening[1] or c == closing[2] and d==opening[2]:
                    pairs+=1

    print(pairs)
            
  
       

count_pairs(exp2)

5


### Question 4:
According to each method's documentation, complete the code of the `TextProcessor` class and its subclass `TextAnalyzer`.

In [86]:
class TextProcessor:
  def __init__(self, text):
    self.text = text
    self.swordslist=[]
  def setStopWords(self, *sWords):
    ''' set stop words as recieved in the parameters '''
    for item in sWords:
        sItem = str(item)
        self.swordslist.append(sItem)
    return print("The stop words are set to:", "".join(map(str,self.swordslist)))
  def getStopWords(self):
    ''' return stop words '''
    return print("The stop words are: ", "".join(map(str,self.swordslist)))
  def getUniqWords(self):
    return set(self.text.split())
  def getFilteredText(self, *fWords):
    ''' remove filter words from the text 
        return filtered text
    '''
    # return print(fWords)
    twordsL = self.text.split()
    filtWords = []
    for fil in fWords: 
        fItem = str(fil)
        filtWords.append(fil)
    for filterword in filtWords:
        if filterword in twordsL:
            twordsL.remove(filterword)
    self.__text=twordsL
    return print(self.text)

class TextAnalyzer(TextProcessor):
    def __init__(self,text):
        TextProcessor.__init__(self,text) 
    
    def getWordFrequency(self):
        
        freqDict = dict()
        filtTextList = self.text.split()
        
        for fword in filtTextList:
            if fword not in freqDict.keys(): 
                freqDict[fword] = 1
            else:
                freqDict[fword] += 1 
        return print(freqDict)
        filtTextList = self.getFilteredText()
        filWordsSplit = filtTextList.split()
        return print(filWordsSplit)
    #for filword in filterText:
    #    if filword not in freqDict.key():
    #        freqDict[filword] = 1
    #    else:
    #        freqDict[filword] +=1

    
    ## CODE HERE ##
 

ta = TextAnalyzer("a quick brown fox " + "a quick brown fox jumps " + "a quick brown fox jumps over " + "a quick brown fox jumps over the " + "a quick brown fox jumps over the lazy " + "a quick brown fox jumps over the lazy dog")
ta.setStopWords(['a','the'])
ta.getWordFrequency()

The stop words are set to: ['Stop', 'please']
The stop words are:  ['Stop', 'please']
Can you please stop Jason
The stop words are set to: ['a', 'the']
{'a': 6, 'quick': 6, 'brown': 6, 'fox': 6, 'jumps': 5, 'over': 4, 'the': 3, 'lazy': 2, 'dog': 1}


Verify the correctness of your code using the following steps:

1. Instantiate the `TextAnalyzer` class by creating an object called `ta` as follows:

`ta = TextAnalyzer("a quick brown fox " + 
                  "a quick brown fox jumps " + 
                  "a quick brown fox jumps over " + 
                  "a quick brown fox jumps over the " + 
                  "a quick brown fox jumps over the lazy " + 
                  "a quick brown fox jumps over the lazy dog")`

2. Assign a list of stop words using the `setStopWords()` method:
`ta.setStopWords(['a', 'the'])`

3. Count the occurrences of each word using the `getWordFrequency()` method:
`ta.getWordFrequency()`

4. The output should be as follows
`{'quick': 6, 'brown': 6, 'fox': 6, 'jumps': 5, 'over': 4, 'lazy': 2, 'dog': 1}}`


#### This is the end of assignment
